//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Question
{
	public virtual char IdRep
	{
		get;
		set;
	}

	public virtual string Contenu
	{
		get;
		set;
	}

	public virtual IEnumerable<Reponse> Reponse
	{
		get;
		set;
	}

	public Question()
	{
	}

	public Question(string contenu)
	{
	}

}

