//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Question
{
    public int IdQuestion { get; set; }
    public virtual int IdReponse
    {
        get;
        set;
    }

    public virtual string Contenu
    {
        get;
        set;
    }
    public int Valeur { get; set; }

    public string ImageAdresse { get; set; }

    public virtual List<Reponse> Reponses
    {
        get;
        set;
    }
    

    public Question()
	{
	}

	public Question(int idQuestion, int idReponse, int valeur, string contenu,string imageAdresse, List<Reponse> reponses)
	{
        IdQuestion = idQuestion;
        IdReponse = idReponse;
        Contenu = contenu;
        Valeur = valeur;
        ImageAdresse = imageAdresse;
        Reponses = new List<Reponse>();
        foreach (var reponse in reponses)
        {
            Reponses.Add(reponse);
        }
        
	}

}

